/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;
import CLS.*;
import javax.swing.*;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

/**
 *
 * @author hneen.
 */
public class SignUp extends javax.swing.JFrame {
    /**
     * Creates new form SignUp
     */
    public SignUp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        FullnameFiled = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        logInjButton1 = new javax.swing.JButton();
        signUpButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        UserNameTextField2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jPasswordField2 = new javax.swing.JPasswordField();
        PhoneTextField3 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(239, 211, 191));

        jLabel1.setIcon(new javax.swing.ImageIcon("icons/bakery_logo2-removebg-preview.png")); // NOI18N

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 0, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(166, 82, 43));
        jLabel2.setText("Sign Up");

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(166, 82, 43));
        jLabel3.setText("Full Name:");

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(166, 82, 43));
        jLabel4.setText("Phone:");

        logInjButton1.setBackground(new java.awt.Color(166, 82, 43));
        logInjButton1.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        logInjButton1.setForeground(new java.awt.Color(255, 255, 255));
        logInjButton1.setText("Log In");
        logInjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logInjButton1ActionPerformed(evt);
            }
        });

        signUpButton2.setBackground(new java.awt.Color(166, 82, 43));
        signUpButton2.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        signUpButton2.setForeground(new java.awt.Color(255, 255, 255));
        signUpButton2.setText("Sign Up");
        signUpButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signUpButton2ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(166, 82, 43));
        jLabel5.setText("User Name:");

        jLabel6.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(166, 82, 43));
        jLabel6.setText("Password:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(51, 51, 51)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addGap(18, 18, 18)
                                                                        .addComponent(UserNameTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addGap(18, 18, 18)
                                                                        .addComponent(jPasswordField2)))
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGap(104, 104, 104)
                                                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(PhoneTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(FullnameFiled, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(66, 66, 66)
                                                .addComponent(logInjButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(48, 48, 48)
                                                .addComponent(signUpButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(83, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(FullnameFiled, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(PhoneTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(UserNameTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jPasswordField2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(33, 33, 33)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(logInjButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(signUpButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(104, 104, 104))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>

    private void logInjButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        dispose();
        loging d= new loging();
        d.setTitle("dashbord");
        d.setVisible(true);
    }

    private void signUpButton2ActionPerformed(java.awt.event.ActionEvent evt) {
        String name=FullnameFiled.getText();
        String phone =PhoneTextField3.getText();
        String username=UserNameTextField2.getText();
        String password=jPasswordField2.getText();

        if(name.isEmpty() || password.isEmpty() || phone.isEmpty() ||  username.isEmpty() || password.isEmpty()){
            JOptionPane.showMessageDialog(this, "should not be empty", "Error", JOptionPane.ERROR_MESSAGE);
        }else{
            //start the login process
            if (PhoneCheck(phone)) {
                usersingup(name, phone,username, password);
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUp().setVisible(true);
            }
        });
    }
    public boolean PhoneCheck(String phone){
        boolean phoneCheck=false;
        if (phone.matches("[0-9]+")){
            if (phone.contains("05")) {
                if (phone.length() == 10) {
                    phoneCheck = true;
                } else {
                    JOptionPane.showMessageDialog(this, "Incorrect Phone number  Please Re-Enter Phone number", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        }
        else  {
            JOptionPane.showMessageDialog(this, "Incorrect Phone number Please Re-Enter Phone number (Just numbers!!)","Error", JOptionPane.ERROR_MESSAGE);
        }
        return phoneCheck;
    }

    private void  usersingup (String name, String phone,String username, String password){
        DB t=new DB();
        Connection dbconn=t.connectDB();
        int last_id=0;
        PreparedStatement st1=null;
        PreparedStatement st=null;
        PreparedStatement insert_id=null;
        PreparedStatement id_p=null;
        ResultSet resultSet=null;
        try {
            id_p=(PreparedStatement) dbconn.prepareStatement("SELECT * FROM person");
            resultSet=id_p.executeQuery();

            while (resultSet.next()){
                last_id = resultSet.getInt("id");
            }
                int id=last_id+1;
                insert_id=(PreparedStatement) dbconn.prepareStatement("insert into person(id) value (?)");
                insert_id.setInt(1,id);
                int res =insert_id.executeUpdate();
                if (res==1){
                    st = (PreparedStatement) dbconn.prepareStatement("insert into customer(coustomer_id,coustomer_name ,coustomer_Phone) values (?,?,?)  ");
                    st.setInt(1, id);
                    st.setString(2, name);
                    st.setString(3, phone);
                    int res2 = st.executeUpdate();
                    if (res2 == 1) {
                        st1 = (PreparedStatement) dbconn.prepareStatement("insert into account(username ,password, person_id, rule) values (?,?,?,?)");
                        st1.setString(1, username);
                        st1.setString(2, password);
                        st1.setInt(3, id);
                        st1.setString(4, "c");
                        int res1 = st1.executeUpdate();
                        if (res1==1)
                            JOptionPane.showMessageDialog(this, "customer Added", "done!", JOptionPane.INFORMATION_MESSAGE);
                    }
                }

//            else  if (employee_radio.isSelected()){
//                int id=last_id+1;
//                insert_id=(PreparedStatement) dbconn.prepareStatement("insert into person(id) value (?)");
//                insert_id.setInt(1,id);
//                int res =insert_id.executeUpdate();
//                if (res==1){
//                    st = (PreparedStatement) dbconn.prepareStatement("insert into employee(Employee_id,Employee_name,Employee_phone) values (?,?,?)  ");
//                    st.setInt(1, id);
//                    st.setString(2, name);
//                    st.setString(3, phone);
//                    int res2 = st.executeUpdate();
//                    if (res2 == 1) {
//                        st1 = (PreparedStatement) dbconn.prepareStatement("insert into account(username ,password,person_id,rule) values (?,?,?,?)");
//                        st1.setString(1, username);
//                        st1.setString(2, password);
//                        st1.setInt(3, id);
//                        st1.setString(4, "e");
//                        int res1 = st1.executeUpdate();
//                        if (res1==1)
//                            JOptionPane.showMessageDialog(this, "Employee Added", "done!", JOptionPane.INFORMATION_MESSAGE);
//                    }
//                }
//            }

        }catch (Exception ex){
            System.out.println(ex.getMessage());
            JOptionPane.showMessageDialog(this, "Error in adding","Error", JOptionPane.ERROR_MESSAGE);
        }finally {
            try {
                dbconn.close();
                insert_id.close();
                resultSet.close();
                id_p.close();
                st.close();
                st1.close();

            }catch (SQLException e){
                e.printStackTrace();
            }
        }

    }


    // Variables declaration - do not modify
    private javax.swing.JTextField FullnameFiled;
    private javax.swing.JTextField PhoneTextField3;
    private javax.swing.JTextField UserNameTextField2;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JButton logInjButton1;
    private javax.swing.JButton signUpButton2;
    // End of variables declaration                   
}
