/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import CLS.DB;
import net.proteanit.sql.DbUtils;

import javax.swing.*;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDate;

/**
 *
 * @author hneen.
 */
public class supplier extends javax.swing.JFrame {

    /**
     * Creates new form supplier
     */
    public supplier() {
        initComponents();
    }
    int id;
    public supplier(int id) {
        initComponents();
        this.id=id;
        setDefault();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        New_nameTextField1 = new javax.swing.JTextField();
        New_ProductTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        NewNamejButton1 = new javax.swing.JButton();
        NewNamejButton2 = new javax.swing.JButton();
        NewProdictjButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(239, 211, 191));

        jLabel1.setIcon(new javax.swing.ImageIcon("/Users/hneen./IdeaProjects/caffe/icons/supplier.png")); // NOI18N

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 0, 36)); // NOI18N
        jLabel2.setText("Supplier Information");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel3.setText("Set New Name to Update:");

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel4.setText("Set New Product to Update:");

        NewNamejButton1.setBackground(new java.awt.Color(166, 82, 43));
        NewNamejButton1.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        NewNamejButton1.setForeground(new java.awt.Color(255, 255, 255));
        NewNamejButton1.setText("Set New Name");
        NewNamejButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewNamejButton1ActionPerformed(evt);
            }
        });

        NewNamejButton2.setBackground(new java.awt.Color(166, 82, 43));
        NewNamejButton2.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        NewNamejButton2.setForeground(new java.awt.Color(255, 255, 255));
        NewNamejButton2.setText("Back");
        NewNamejButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewNamejButton2ActionPerformed(evt);
            }
        });

        NewProdictjButton3.setBackground(new java.awt.Color(166, 82, 43));
        NewProdictjButton3.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        NewProdictjButton3.setForeground(new java.awt.Color(255, 255, 255));
        NewProdictjButton3.setText("Set New Product");
        NewProdictjButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewProdictjButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 746, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(New_nameTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(NewNamejButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(44, 44, 44)))
                        .addGap(158, 158, 158)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(New_ProductTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(267, 267, 267)
                        .addComponent(NewNamejButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(64, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(479, Short.MAX_VALUE)
                    .addComponent(NewProdictjButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(174, 174, 174)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(New_nameTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(NewNamejButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(New_ProductTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(38, 38, 38)
                .addComponent(NewNamejButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(421, Short.MAX_VALUE)
                    .addComponent(NewProdictjButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(118, 118, 118)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        

    private void NewNamejButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        if (jTable1.getSelectedRow()>=0) {
            int getIdE = -1;
            int row = jTable1.getSelectedRow();
            getIdE = Integer.parseInt(jTable1.getModel().getValueAt(row, 0).toString());
            String name =null;
            name =New_nameTextField1.getText();
            if (!name.equals("")){
                        if (getIdE != -1) {
                            setName(getIdE, name);
                        }
            }
            else {
                JOptionPane.showMessageDialog(this, "Set the Name first!", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }else {
            JOptionPane.showMessageDialog(this, "Select Supplier to Update!", "Error", JOptionPane.ERROR_MESSAGE);
        }    }

    private void NewProdictjButton3ActionPerformed(java.awt.event.ActionEvent evt) {
        if (jTable1.getSelectedRow()>=0) {
            int getIdE = -1;
            int row = jTable1.getSelectedRow();
            getIdE = Integer.parseInt(jTable1.getModel().getValueAt(row, 0).toString());
            String Product =null;
            Product =New_ProductTextField2.getText();
            if (!Product.equals("")){
                if (getIdE != -1) {
                    setProduct(getIdE, Product);
                }
            }
            else {
                JOptionPane.showMessageDialog(this, "Set the Name of the Product first!", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }else {
            JOptionPane.showMessageDialog(this, "Select Supplier to Update!", "Error", JOptionPane.ERROR_MESSAGE);
        }    }


    private void NewNamejButton2ActionPerformed(java.awt.event.ActionEvent evt) {
        dispose();
        manger d= new manger(id,"m");
        d.setTitle("Manager");
        d.setVisible(true);
    }


    void setName(int id ,String Name){
        DB conn = new DB();
        Connection dbconn = conn.connectDB();
        PreparedStatement update=null;
        try{
            LocalDate today =  LocalDate.now();             //Today
            LocalDate PayDate = today.plusDays(14);
            java.sql.Date d = java.sql.Date.valueOf( PayDate ) ;

            update=dbconn.prepareStatement("UPDATE supplier SET supplier_name =? WHERE (supplier_id =?)");
            update.setString(1,Name);
            update.setInt(2,id);
            int doUpdate = update.executeUpdate();
            if (doUpdate==1){
                JOptionPane.showMessageDialog(this, "Update done!", "successful", JOptionPane.INFORMATION_MESSAGE);
                setDefault();
            }
        }catch (Exception e){
            e.printStackTrace();
        }finally {
            try{
                dbconn.close();
                update.close();
            }catch (SQLException e){
                e.printStackTrace();
            }
        }
    }
    void setProduct(int id ,String Product){
        DB conn = new DB();
        Connection dbconn = conn.connectDB();
        PreparedStatement update=null;
        try{
            LocalDate today =  LocalDate.now();             //Today
            LocalDate PayDate = today.plusDays(14);
            java.sql.Date d = java.sql.Date.valueOf( PayDate ) ;

            update=dbconn.prepareStatement("UPDATE supplier SET Product =? WHERE (supplier_id =?)");
            update.setString(1,Product);
            update.setInt(2,id);
            int doUpdate = update.executeUpdate();
            if (doUpdate==1){
                JOptionPane.showMessageDialog(this, "Update done!", "successful", JOptionPane.INFORMATION_MESSAGE);
                setDefault();
            }
        }catch (Exception e){
            e.printStackTrace();
        }finally {
            try{
                dbconn.close();
                update.close();
            }catch (SQLException e){
                e.printStackTrace();
            }
        }
    }

    void setDefault(){
        DB conn=new DB();
        Connection dbconn=conn.connectDB();
        PreparedStatement selectAll=null;
        ResultSet selectE=null;
        try {
            selectAll = dbconn.prepareStatement("SELECT * FROM supplier");
            selectE= selectAll.executeQuery();
            jTable1.setModel(DbUtils.resultSetToTableModel(selectE));
        } catch (SQLException e) {
            e.printStackTrace();
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(supplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(supplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(supplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(supplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new supplier().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton NewNamejButton1;
    private javax.swing.JButton NewNamejButton2;
    private javax.swing.JButton NewProdictjButton3;
    private javax.swing.JTextField New_ProductTextField2;
    private javax.swing.JTextField New_nameTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration                   
}
